name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install

      - name: Restore lint cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .ruff_cache
            .mypy_cache
          key: "${{ runner.os }}-lint-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-lint-

      - name: Run lint
        run: poetry run ruff check

      - name: Run type check
        run: poetry run mypy .

      - name: Save lint cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            .ruff_cache
            .mypy_cache
          key: "${{ runner.os }}-lint--${{ github.sha }}"
